#!/bin/sh -e

cd "$(dirname "$0")"
ROOT_PATH=$(pwd -P)

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}
success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}
fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

link_data_file(){
  SOUR="$1"
  DEST="$2"
  if [ -n "$SOUR" ] ;
      then
          if [ -n "$DEST" ] ;
              then
                  ln -s -f "$SOUR" "$DEST"
                  success "$DEST""\t-->\t""$SOUR"
              else
                  fail "Destination Path is NULL - Use As link_data_file \"Source\" \"Destination\""
                  exit
          fi
      else
          fail "Source Path is NULL - Use As link_data_file \"Source\" \"Destination\""
          exit
  fi
}

info "-------------------------------------------------------------------------"
info "#########################################################################"
info "#"
info "#\t\t 1_Functions"
info "#"
info "#########################################################################"
info ""
info "Current Directory:\t"$ROOT_PATH
info ""
for src in $(find "$ROOT_PATH" -maxdepth 2 -name '*.sh' -not -path '*.git*')
  do
    DESTINATION_PATH="/usr/local/bin/"$(basename "${src%.*}")
    SOURCE_PATH=$src
    link_data_file "$SOURCE_PATH" "$DESTINATION_PATH"
done
info ""
info "-------------------------------------------------------------------------"