#!/bin/sh
set -e
#locate MacConfig Path
cd "$(dirname "$0")"
ROOT_PATH=$(pwd -P)

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}
success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}
fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

##################################################################################################
# Install Brew Software
info ""
info "-------------------------------------------------------------------------"
info ""
info " > Installing Brew.."
info ""
if test ! $(which brew)
	then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	success "# brew install success"
	else
		fail "# brew already installed"
fi

# Install Shell oh-my-zsh
info ""
info "-------------------------------------------------------------------------"
info "> Installing oh-my-zsh.."
info ""
if [ ! -d ~/.oh-my-zsh ]
  then
    curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
    success "# oh-my-zsh installed success"
	else
  	fail "# oh-my-zsh already installed"
fi

##################################################################################################

# 1. Load Common Functions
$ROOT_PATH"/1_Functions/install"

# 2. Link Base Files & Install Plugs
$ROOT_PATH"/2_BasePlugs/install"

# 3. Link Data Files
$ROOT_PATH"/3_LinkFiles/install"

# 4. Link Dot Files
$ROOT_PATH"/4_DotFiles/install"

# 5. OSX Config
$ROOT_PATH"/5_OSX/install"

# 6. Install Brew Software
$ROOT_PATH"/6_Brew/install"

# 7. Install Necessary Scripts
$ROOT_PATH"/7_Run/install"

info "<<<<<<<<<<<<< End"