#!/bin/sh -e

cd "$(dirname "$0")"
ROOT_PATH=$(pwd -P)

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}
success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}
fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

#-------------------------------------------------------------------------------
# 安装Brew软件包管理器，以及oh-my-zsh shell终端
# Brew软件包管理器比较方便，个人觉得还是安装，另外还能配置成开发模式，安装xcode tool、创建 /usr/local/bin目录等
# oh-my-zsh 如果习惯用自带的bash的话可以不安装这个
# 添加一些基本shell方法到 "/usr/local/bin" 作为全局函数使用 (例如：ssh自动登录脚本)
#-------------------------------------------------------------------------------
info ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Script Begin >>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
info ""
info "-------------------------------------------------------------------------"
info " > Install Brew package manager for macOS (https://brew.sh/)"
info " > 安装Brew软件包管理器"
info "-------------------------------------------------------------------------"
info ""
if test ! $(which brew)
  then
    info " > Installing Brew.."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    success "# brew install success"
  else
    fail "# brew already installed"
fi
info ""
info "-------------------------------------------------------------------------"
info " > Install oh-my-zsh for macOS (https://ohmyz.sh/)"
info " > 安装Shell(oh-my-zsh)"
info "-------------------------------------------------------------------------"
info ""
if [ ! -d ~/.oh-my-zsh ]
  then
    info "> Installing oh-my-zsh.."
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    success "# oh-my-zsh installed success"
  else
    fail "# oh-my-zsh already installed"
fi
info "-------------------------------------------------------------------------"

sudo -v

#-------------------------------------------------------------------------------
# 1. Add Common Shell Functions To "/usr/local/bin" (e.g "ssh_login expect")
# 1. 添加一些基本shell方法到 "/usr/local/bin" 作为全局函数使用 (例如：ssh自动登录脚本)
#-------------------------------------------------------------------------------

$ROOT_PATH"/1_Functions/install"

#-------------------------------------------------------------------------------
# 2. Link Basic File Path (e.g. Link Data&&Conifg to $HOME)
# 2. 软链接一些之后脚本需要用到的目录结构 (例如：配置文件或者app数据文件 链接到 主目录下)
#-------------------------------------------------------------------------------

$ROOT_PATH"/2_BasePlugs/install"

#-------------------------------------------------------------------------------
# 3. Link Data File Path (e.g. Private Data In Dropbox)
# 3. 软链接数据文件以及app配置数据 (例如：QQ聊天记录或其他不需要上传到github，存储在Dropbox中的一些配置)
#-------------------------------------------------------------------------------

$ROOT_PATH"/3_LinkFiles/install"

#-------------------------------------------------------------------------------
# 4. Dot Files (Public Data, Dotfile In Github)
# 4. 可以存储在Github上的dotfiles
#-------------------------------------------------------------------------------

$ROOT_PATH"/4_DotFiles/install"

#-------------------------------------------------------------------------------
# 5. macOS Conifg (10.13.4)
# 5. 苹果系统设置脚本
#-------------------------------------------------------------------------------

$ROOT_PATH"/5_OSX/install"

#-------------------------------------------------------------------------------
# 6. Install Brew Software
# 6. 安装Brew软件 (一些通过brew安装的软件可以在这里配置)
#-------------------------------------------------------------------------------
#$ROOT_PATH"/6_Brew/install"

#-------------------------------------------------------------------------------
# 7. Run Script
# 7. 运行一些剩余的脚本 (例如：软件安装切换到任何来源)
#-------------------------------------------------------------------------------

$ROOT_PATH"/7_Run/install"

info "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Script End <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"