#!/bin/sh
set -e
cd "$(dirname "$0")"
ROOT_PATH=$(pwd -P)

source message

info "-------------------------------------------------------------------------"
info "#########################################################################"
info "#"
info "#\t\t 2_BasePlugs"
info "#"
info "#########################################################################"
info ""
info "Current Directory:\t"$ROOT_PATH
info ""
for src in $(find "$ROOT_PATH" -maxdepth 2 -name '*.sh' -not -path '*.git*')
	do
		$src
done
info ""
info "-------------------------------------------------------------------------"