#!/bin/sh
#设置QQ用户目录
#QQ_SOURCE_PATH 源地址
#QQ_DESTINATION_PATH 目的地址
#脚本会删除源地址的QQ目录，并将目的地址软链到源地址，请做好备份!
QQ_SOURCE_PATH='/Users/semoz/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ'
QQ_DESTINATION_PATH='/Volumes/Mac_Data/FileData/QQ'

link_qq_path () {
if [ -d "$QQ_SOURCE_PATH" ]; then
	rm -r "$QQ_SOURCE_PATH"
	# 删不掉的话只能用强制删除了
	#rm -rf "$QQ_SOURCE_PATH"
	sudo ln -s -f "$QQ_DESTINATION_PATH" "$QQ_SOURCE_PATH"
else
	echo "QQ file not exist ~ quit!"
fi
#open '/Users/semoz/Library/Containers/com.tencent.qq/Data/Library/Application Support'
}

yes_or_no() {
    echo "this script will delete QQ source path, please backup!"
   while true
   do
    echo "Enter yes or no : "
   read x
   case "$x" in
   y|yes ) return 0;;
   n|no  ) return 1;;
   * ) echo "Answer yes or no!"
   esac
   done
}

if yes_or_no "$1"
then
  link_qq_path
else
  echo "goodbye"
fi
exit 0