#!/bin/sh -e

cd "$(dirname "$0")"
DOTFILES_ROOT=$(pwd -P)

source message

#-----------------------------------------------------------------------------
# link dotfiles
# 软链接dotfile
#-----------------------------------------------------------------------------

for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
do
  dst="$HOME/.$(basename "${src%.*}")"
  link_data_file "$src" "$dst"
done