#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# 以下功能 详见https://coderwall.com/p/afmnbq/homebrew-s-new-feature-brewfiles
# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# 查找所有的install.sh 并安装
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done


gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
