#!/bin/sh
set -e
cd "$(dirname "$0")"
ROOT_PATH=$(pwd -P)
info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}
success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}
fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}
info "-------------------------------------------------------------------------"
info "#########################################################################"
info "#"
info "#\t\t macOS Configuration"
info "#"
info "#########################################################################"
info ""
info "Current Directory:\t"$ROOT_PATH
info ""
for src in $(find "$ROOT_PATH" -maxdepth 2 -name '*.sh' -not -path '*.git*')
	do
		info "Config.. "$(basename "${src%.*}")
		$src
done
info ""
info "-------------------------------------------------------------------------"